config/routes.rb
Rails.application.routes.draw do
  
  root 'welcome#home'
  devise_for :user, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks"}
  get 'signup', to: "users#new"
  resources :users, except: [:new] do
		resources :matches
    resources :teams
  end
  resources :notifications, only: [:index]
  get 'login', to: "sessions#new"
  post 'login', to: "sessions#create"
  delete 'logout', to: "sessions#destroy"
  get '/users/:user_id/show/:id', to: "users#show_user", as: "user_show_user"
  get '/users/:user_id/search/', to: "users#search", as: "user_search"

  post '/users/:id/matches/:match_id/leavet/:team_id', to: "matches#leaveteam"
  get '/users/:id/matches/:match_id/leavep', to: "matches#leaveplayer"
  get '/users/:id/matches/:match_id/destroy', to: "matches#destroy"
  post '/users/:user_id/matches/:match_id/aggiungi', to: "matches#aggiungi"
  post '/users/:id/matches/:match_id/endgame', to: "matches#endgame"
  post '/users/:id/matches/:match_id/rate', to: "matches#rate"
  post 'findplaces', to: "matches#findcourts"

  get '/users/:id/matches/:match_id/redirect', to: 'matches#redirect', as: 'redirect'
  get '/callback', to: 'matches#callback', as: 'callback'
  
  post '/users/:id/updateD', to: "users#updateD"
  post '/users/:id/updateR', to: "users#updateR"

  get '/matches/near', to: "matches#near", as: "matches_near"
  put '/users/:user_id/teams/:id/leave', to: "teams#leave", as: "teams_leave"
  put '/users/:user_id/teams/:team_id/remove/:user', to: "teams#remove", as: "teams_remove"
  put '/users/:user_id/teams/:team_id/captain/:user', to: "teams#captain", as: "teams_captain"
  put '/users/:user_id/teams/:team_id/invite', to: "teams#invite", as: "teams_invite"
  get '/notifications/:id/accept', to: "notifications#accept", as: "notifications_accept"
  get '/notifications/:id/deny', to: "notifications#deny", as: "notifications_deny"
  get '/users/:id/matches/mode/new', to: "matches#mode", as: "new_mode_user_match"
  put '/users/:id/matches/:match_id/deleteplayer/:user_id_2', to: "matches#deleteplayer", as: "matches_delete_player"
  put '/users/:id/matches/:match_id/deleteteam/:team_id', to: "matches#deleteteam", as: "matches_delete_team"



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/match.rb
class Match < ApplicationRecord

	acts_as_mappable :default_units => :kms,
                   :default_formula => :sphere,
                   :distance_field_name => :distance,
                   :lat_column_name => :lat,
                   :lng_column_name => :lng


	belongs_to :creatore, class_name: "User"
	has_one :uu, dependent: :destroy
	has_one :pt, dependent: :destroy
	has_one :tt, dependent: :destroy


	def is_waiting_response_for_role(role,squadra)
		if squadra
			n = Par.where(match_id: self.id, ruolo: role, squadra: squadra)
			return !n.empty?
		end
		n = Par.where(match_id: self.id, ruolo: role)
		return !n.empty?
	end

	def is_waiting_response_for_team
		n = Par.where(match_id: self.id).where.not(team: nil)
		return !n.empty?
	end

	def is_in_match?(user)
		if self.uu
			return !self.uu.gioca.where(user_id: user.id).empty?
		elsif self.pt
			if self.pt.team[0]
				return ((self.pt.team[0].is_in_team?user) || (!self.pt.squadra.where(user_id: user.id).empty?))
			end

			!self.pt.squadra.where(user_id: user.id).empty?
		else
			bool = false
			self.tt.team.each do |t|
				bool = (bool || (t.is_in_team?user))
			end
			return bool
		end
	end


	
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController

	skip_before_action :verify_authenticity_token 
	before_action :require_user, except: [:near] 

	def new
		@user = User.find_by(id: params[:user_id])
		@match = Match.new
		@match.lat = params[:lat].to_f
		@match.lng = params[:lng].to_f
		@match.campo = params[:nome]
		if params[:commit] == "SoloVsSolo"
			render :template => "/matches/playsolovssolo"
			return
		elsif params[:commit] == "SquadraVsSolo"
			render :template => "/matches/playsquadravssolo"
			return
		elsif params[:commit] == "SquadraVsSquadra"
			render :template => "/matches/playsquadravssquadra"
			return
		end
		redirect_to user_matches_path current_user
	end

	def aggiungi
		@match=Match.find_by(id: params[:match_id])
		if(@match.uu !=nil)
			puts @match.uu.user.where(id: params[:user_id]).empty?
			if(@match.uu.user.where(id: params[:user_id]).empty?)
			    Gioca.create(user_id: params[:user_id],ruolo: params[:ruolo],squadra: params[:squadra], uu_id: @match.uu.id)	
			end
		elsif (@match.pt !=nil)
			if(params[:team]!= "")
				@team = Team.find_by(nome: params[:team])
				if(@team==nil) 
					puts "Team A non trovato!" 
					redirect_to user_matches_path current_user
					return
			    end
			    if(@team.capitano_id.to_i == params[:user_id].to_i && @match.pt.user.where(id: params[:user_id])[0] == nil)
			    	@team.pt << @match.pt
			    	@team.save
			    end
			else
				if(@match.pt.user.where(id: params[:user_id])[0] == nil )
					if( @match.pt.team[0]==nil || @match.pt.team[0].user.where(id: user.id)[0]==nil) 
			    	Squadra.create(user_id: params[:user_id],ruolo:params[:ruolo],pt_id: @match.pt.id)	
			    	end
				end
			end
		else
			if( (@match.tt.team[0]==nil||@match.tt.team[0].user.where(id: params[:user_id])[0]==nil) && (@match.tt.team[1]==nil||@match.tt.team[1].user.where(id: params[:user_id])[0]==nil))
				@team = Team.find_by(nome: params[:team])
				if(@team.capitano_id.to_i == params[:user_id].to_i)
					@team.tt << @match.tt
					@team.save
				end
			end
		end
		redirect_to user_matches_path current_user
		
	end
	#Questa action permette di vedere in dettaglio la partita distinta da id_match definito nella url. Prima controllo che 
	#lo user partecipi effettivamente al match, altrimenti lo rimando su root. Se il test viene verificato allora:
	#-Se la partita è uu mi prendo la collezione dei gioca associati a quella partita così da avere tutti gli utenti che 
	#partecipano alla partita e anche i ruoli da poter far vedere
	#-Se la partita è pt mi prendo la collezione dei squadra associata a quella partita così da avere tutti gli utenti singoli che 
	#partecipano a quella partita. Inoltre se è stata assegnata una squadra a pt, allora dalla squadra mi prendo tutti i membro 
	#di quella squadra codì da poter risalire velocemente agli user di quella squadra che partecipano alla partita con i ruoli
	#definiti dalla loro auuartenenza alla squadra
	#-Se la partita è tt, allora controllo se ho entrambe le squadre e di ogni squadra mi prendo le relazioni membro così da avere
	#i giocatori che partecipano alla partita con i loro rispettivi ruoli che coincidono con quelli della loro associazione con
	#la squadra di auuartenenza

	def mode
		@user = User.find_by(id: params[:id])
	end

	def show
		puts "CAZZOOOOOOOOOOOOOOOO"
		@user = User.find_by id: params[:user_id]
		@m = Match.find_by id: params[:id]
		puts @m.pt.team[0].is_in_team?@user
		puts !@m.pt.squadra.where(user_id: @user.id).empty?
		puts can? :show, @m
		authorize! :show, @m, :message => "Non sei autorizzato a vedere questa partita"
		if @m.tipo == 1
			@players = @m.uu.gioca
		elsif @m.tipo == 2
			@single_players = @m.pt.squadra
			if @m.pt.team[0] != nil
				@team_players = @m.pt.team[0].membro
			end
		elsif @m.tipo == 3
			if @m.tt.team.size == 1
				@players_team_1 = @m.tt.team[0].membro
			else
				@players_team_1 = @m.tt.team[0].membro
				@players_team_2 = @m.tt.team[1].membro
			end
		end
			
			
	end

	#Con questo metodo restituisco tutti i match in cui un giocatore è presente o come utente singolo o come componente di una
	#squadra. Restituisco un array di oggetti Match da cui posso poi risalire a tutti i vari componenti utili di un match se 
	#devo mostrare informazioni aggiuntive
	#dalla url mi estraggo l'id dell'user e lo trovo nel database. In seguito mi trovvo prima tutti i uu a cui partecipa e 
	#da questi mi prendo i match a cui si riferiscono. Dopo prendo tutti i pt a cui partecipa come utente singolo e mi prendo
	#il match corrispondente. In seguito mi prendo tutti i team a cui partecipa. Per ogni team mi prendo tutti i pt a cui partecipa 
	#e i match in cui è stata inserita la squadra e quindi i match pt a cui partecipa l'user tramite la squadra. Di ogni squadra
	#mi prendo anche i tt a cui partecipa e quindi il match corrispondente a cui partecipa l'utente che partecipa a quella squadra

	def index
		@user = User.find_by id: params[:user_id]
		matches_uu = @user.uu
		matches_pt_s = @user.pt
		@user_teams = @user.team
		@matches = Array.new
		matches_uu.each do |p|
			@matches.push p.match
		end
		matches_pt_s.each do |p|
			@matches.push p.match
		end
		@user_teams.each do |t|
			t.pt.each do |p|
				@matches.push p.match
			end
			t.tt.each do |tt|
				@matches.push tt.match
			end
		end
		puts @matches
	end

	#mi arriva la get a questa route e in params ho location che viene mandata come query
	#chiamo find cordinates e mi trovo lat e lng che viene passato come un array di due elementi se tutto andato bene
	#faccio una query sul modello Match per fare in modo di trovare solo le partite che sono nel raggio di quelle coordinate
	#la query la faccio tramite geokit e trovo le partite nel raggio di 3 km dalle coordinate selezionate
	#Oltre alla query spaziale sul modelli Match devo prendere anche quelle partite che non sono complete e per questo faccio
	#3 query differenti in base alla sottomodello che il modello Match è legato.
	#Considero la prima query che le altre 2 sono simili.
	#Faccio una join tra match, uu e gioca e le raggruuuo per uus.id,matches.id e conto quante istanze della relazione gioca
	#contiene un certo uus.id(dato che ho fatto la group) e prendo solo quelli che il conto è minore di 10, perchè vuol dire 
	#che ci sono ancora dei posti disponibili per qualche giocatore
	#Dopo le query creo un hash che ha come chiave l'id di un match e come valore i ruoli disponibili per quel match, trovati
	#tramite la funzione di ausilio "find_roles_left" e passo questo hash come variabile di istanza così che è accessibile 
	#dalla view

	def near

		address = params[:address].split(",")[0]
		city = params[:address].split(",")[1]
		coordinates = find_coordinates address, city
		if coordinates.length == 1
			puts coordinates[0]
			redirect_to root_path
		else
			if logged_in?
				@matches_uu = Match.within(5, :origin => coordinates).where(tipo: 1).select{|m|
					((Date.today <=> m.data) == -1) &&
					m.uu.gioca.size < 10 &&
					(m.uu.gioca.where(ruolo: current_user.ruolo1).empty? ||
					m.uu.gioca.where(ruolo: current_user.ruolo2).empty?) &&
					m.uu.gioca.where(user_id: current_user.id).empty? &&
					m.uu.gioca.where(user_id: current_user.id).empty?
				}
				@matches_pt = Match.within(5, :origin => coordinates).where(tipo: 2).select{|m|
					((Date.today <=> m.data) == -1) &&
					(m.pt.team.empty? ||
					 m.pt.squadra.size < 5  &&
					(m.pt.squadra.where(ruolo: current_user.ruolo1).empty? ||
					m.pt.squadra.where(ruolo: current_user.ruolo2).empty?) &&
					m.pt.squadra.where(user_id: current_user.id).empty? &&
					!m.pt.team[0].is_in_team?(current_user))
				}
				@matches_tt = Match.within(5, :origin => coordinates).where(tipo: 3).select{|m| 
					((Date.today <=> m.data) == -1) &&
					(m.tt.team[0] == nil && !m.tt.team[1].is_in_team?(current_user)) ||
					(m.tt.team[1] == nil && !m.tt.team[0].is_in_team?(current_user))
				}

				@roles_left_uu = Hash.new
				@matches_uu.each do |m_uu|
					@roles_left_uu["#{m_uu.id}"] = find_roles_left(m_uu).select{|r| r[1] == current_user.ruolo1 || r[1,r.length-1] == current_user.ruolo2}
					
				end
				@roles_left_pt = Hash.new
				@matches_pt.each do |m_pt|
					@roles_left_pt["#{m_pt.id}"] = find_roles_left(m_pt).select{|r| r == current_user.ruolo1 || r == current_user.ruolo2}
				end
			else
				@matches_uu = Match.within(5, :origin => coordinates).where(tipo: 1).select{|m|
					(Date.today <=> m.data) == -1 &&
					m.uu.gioca.size < 10
				}
				@matches_pt = Match.within(5, :origin => coordinates).where(tipo: 2).select{|m|
					(Date.today <=> m.data) == -1 &&
					(m.pt.squadra.size < 5 ||
					 m.pt.team.empty?)
				}
				@matches_tt = Match.within(5, :origin => coordinates).where(tipo: 3).select{|m| 
					(Date.today <=> m.data) == -1 &&
					(m.tt.team[0] != nil) ||
					(m.tt.team[1] != nil)
				}
				@roles_left_uu = Hash.new
				@matches_uu.each do |m_uu|
					@roles_left_uu["#{m_uu.id}"] = find_roles_left(m_uu)
				end
				@roles_left_pt = Hash.new
				@matches_pt.each do |m_pt|
					@roles_left_pt["#{m_pt.id}"] = find_roles_left(m_pt)
				end
			end
		end
		
	end

	#TROVA CAMPI
	def findcourts
		address = params[:address].split(",")[0]
		city = params[:address].split(",")[1]
		coordinates = find_coordinates address, city
		response=HTTParty.get('https://maps.googleapis.com/maps/api/place/nearbysearch/json?keyword=calcetto&location='+coordinates[0].to_s+','+coordinates[1].to_s+
      '&radius=3000&key=AIzaSyDcD5M36rW3mAStLyxu3gsjwhOwi_LmHvI')
		r = JSON.parse response.body
		@array=Array.new
		r["results"].each do |t|
			puts t
			puts t["geometry"]["location"]["lng"]
			puts t["geometry"]["location"]["lat"]
			elem = {"lng" => t["geometry"]["location"]["lng"],"lat" => t["geometry"]["location"]["lat"],"nome" => t["name"], "address" => t["vicinity"]}
			@array.push elem
		end
	end

    #CREA EVENTO
	def create
		    if(params[:tipo]=="uu")
		    	user=User.find_by(id: params[:user_id])
		    	b=false
				params.each do |k,v|

app/helpers/matches_helper.rb
module MatchesHelper
end

app/views/matches/_courts.html.haml
%ul.list-group
  - @array.each do |court|
    %li.list-group-item
      .row
        .col-6
          = court["nome"]
        .col-6
          = court["address"]
      .row
        = form_tag "/users/#{current_user.id}/matches/new", method: "get" do
          .form-group
            = text_field_tag "lat",nil, class: "form-control", placeholder: "Inserisci indirizzo", autofocus: true, :style => "display: none", value: "#{court["lat"]}"
            = text_field_tag "lng",nil, class: "form-control", placeholder: "Inserisci indirizzo", autofocus: true, :style => "display: none", value: "#{court["lng"]}"
            = text_field_tag "nome",nil, class: "form-control", placeholder: "Inserisci indirizzo", autofocus: true,:style => "display: none", value: "#{court["nome"]}"
            %br/
            .container{:style => "margin-left: 2%"}
              = submit_tag "SoloVsSolo", class: "btn btn-primary"
              = submit_tag "SquadraVsSolo", class: "btn btn-primary"
              = submit_tag "SquadraVsSquadra", class: "btn btn-primary"

app/views/matches/deleteteam.js.haml
- if @m.tipo == 2
	$("##{@m.id}_1").html("#{j(render("showsquadravssolo"))}")
- elsif @m.tipo == 3
	$("##{@m.id}_1").html("#{j(render("showsquadravssquadra"))}")

app/views/matches/endgame.js.haml
- if @m.tipo == 1
	$("##{@m.id}_1").html("#{j(render("showsolovssolo"))}")
- elsif @m.tipo == 2
	$("##{@m.id}_1").html("#{j(render("showsquadravssolo"))}")
- elsif @m.tipo == 3
	$("##{@m.id}_1").html("#{j(render("showsquadravssquadra"))}")
	

app/views/matches/findcourts.js.haml
$("#court").html("#{j(render("courts"))}")

app/views/matches/index.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title indexeventi
    %link{:crossorigin => "anonymous", :href => "https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css", :integrity => "sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB", :rel => "stylesheet"}/
    = stylesheet_link_tag "mostraeventi1.css"
    = stylesheet_link_tag "index_team.css"
    = stylesheet_link_tag "mostraeventi.css"
    %link{:crossorigin => "anonymous", :href => "https://use.fontawesome.com/releases/v5.0.13/css/all.css", :integrity => "sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp", :rel => "stylesheet"}/
    %link{:href => "https://fonts.googleapis.com/css?family=Merriweather+Sans", :rel => "stylesheet"}/
  %body{:style => "font-family: 'Merriweather Sans', sans-serif; margin-left: 0.9%; margin-right: 0.9%;"}
    .row
      %nav.navbar.navbar-light.barra
        .col-3
          .container
            = form_tag "/matches/near", method: :get, :class => "form-inline" do
              %input.form-control.mr-sm-2{"aria-label" => "Search", :placeholder => "Search", :style => "width: 48%;", :type => "search", :name => "address"}/
              %button.btn.btn-outline-success.my-2.my-sm-0{:type => "submit"} Search
        .col-3
          %a{:href => "/users/#{@user.id}"}
            %b Profile
            - if @user.unread_notifications.size > 0
              %span.badge.badge-light 
                = @user.unread_notifications.size
        .col-3
          %a{:href => "/users/#{@user.id}/matches/mode/new"}
            %b Play
        .col-3
          %a{:href => "/users/#{@user.id}/matches"}
            %b Home
    .row
      .col-2.border-right{:style => "margin-left: 1.4%"}
        .container.user_column
          = image_tag("#{@user.img}",height: '130', width: '130', align: "center", id: "image", class: "user_column_obj")
        .container.user_column
          %p.user_column_obj
            %b#nick Nickname:
            = @user.nick
        .container.user_column
          %p.user_column_obj
            %b#val Valutazione:
            - if @user.voto != 0
              = (@user.voto/@user.tot).round(1)
            - else
              0
        .container.user_column
          %a.user_column_obj{:href => "#"}
            %b
              = link_to "Teams", user_teams_path(@user)
        .container.user_column
          %a.user_column_obj{:href => "#"}
            %b 
              = link_to "Logout", logout_path, method: :delete
        .container.user_column
          = form_tag "/users/#{@user.id}/search", method: "get" do
            .row
              .col-12
                .row
                  %input.form-control{:name => "nome", :placeholder => "Cerca utente", :type => "", :style => "width: 80%;"}/
                  %button.btn.btn-outline-dark{:type => "submit"}
                    %i.fas.fa-search
      .col-7
        - if @matches.empty?
          .row
            .col-4
            .col-4
              .container{:style => "margin-top: 50%"}
                .alert.alert-danger{:role => "alert"}
                  Non partecipi a nessun Match
        - else
          - @matches.each do |m|
            .row
              .container
                .card.index-teams{:style => "width: 50rem;"}
                  .card-body.prova{:id => "#{m.id}_1"}
                    - if m.tipo == 1
                      %h5.card-title Players Vs Players
                    - elsif m.tipo == 2
                      %h5.card-title Players Vs Team
                    - elsif m.tipo == 3
                      %h5.card-title Team Vs Team
                    Status:
                    - if (Date.today <=> m.data) == -1
                      Da giocare
                    - elsif (Date.today <=> m.data) == 0
                      Giorno della partita
                    - else (Date.today <=> m.data) == 1
                      Terminato
                    %p.card-text
                      .row
                        .col-4
                          Creatore:
                          = m.creatore.nick
                        .col-4
                          %input#set1{:min => "0", :step => "1", :type => "number", disabled: true, value: "#{m.punt1}"}/
                          %input#set1{:min => "0", :step => "1", :type => "number", disabled: true, value: "#{m.punt2}"}/ 
                        .col-4
                          %a.btn.btn-outline-dark{ :href => "/users/#{@user.id}/matches/#{m.id}", "data-remote" => "true"}
                            %i.fas.fa-info-circle.fa-2x

app/views/matches/mode.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title modalitadigioco
    %link{:crossorigin => "anonymous", :href => "https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css", :integrity => "sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB", :rel => "stylesheet"}/
    = stylesheet_link_tag "mostraeventi.css"
    = stylesheet_link_tag "index_team.css"
    = stylesheet_link_tag "modalitaplay.css"
    %link{:crossorigin => "anonymous", :href => "https://use.fontawesome.com/releases/v5.0.13/css/all.css", :integrity => "sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp", :rel => "stylesheet"}/
    %link{:href => "https://fonts.googleapis.com/css?family=Merriweather+Sans", :rel => "stylesheet"}/
  %body{:style => "font-family: 'Merriweather Sans', sans-serif; margin-left: 0.9%; margin-right: 0.9%;"}
    .row
      %nav.navbar.navbar-light.barra
        .col-3
          .container
            = form_tag "/matches/near", method: :get, :class => "form-inline" do
              %input.form-control.mr-sm-2{"aria-label" => "Search", :placeholder => "Search", :style => "width: 48%;", :type => "search", :name => "address"}/
              %button.btn.btn-outline-success.my-2.my-sm-0{:type => "submit"} Search
        .col-3
          %a{:href => "/users/#{@user.id}"}
            %b Profile
            - if @user.unread_notifications.size > 0
              %span.badge.badge-light 
                = @user.unread_notifications.size
        .col-3
          %a{:href => "/users/#{@user.id}/matches/mode/new"}
            %b Play
        .col-3
          %a{:href => "/users/#{@user.id}/matches"}
            %b Home
    .row
      .col-2.border-right{:style => "margin-left: 1.4%"}
        .container.user_column
          = image_tag("#{@user.img}",height: '130', width: '130', align: "center", id: "image", class: "user_column_obj")
        .container.user_column
          %p.user_column_obj
            %b#nick Nickname:
            = @user.nick
        .container.user_column
          %p.user_column_obj
            %b#val Valutazione:
            - if current_user.voto != 0
              = (current_user.voto/current_user.tot).round(1)
            - else
              0
        .container.user_column
          %a.user_column_obj{:href => "#"}
            %b
              = link_to "Teams", user_teams_path(@user)
        .container.user_column
          %a.user_column_obj{:href => "#"}
            %b 
              = link_to "Logout", logout_path, method: :delete
      .col-6
        #intestazione
          %p{:align => "center", :style => "font-size: 40px"}
            %b Cerca struttura:
          %br/
          = form_tag "/findplaces", method: "post", remote: true do
            .form-group
              = text_field_tag "address",nil, class: "form-control", placeholder: "Inserisci nome struttura", autofocus: true
              #setbutt
                %button.btn.btn-primary{:type => "submit", :style => "margin-left: 2%"} 
                  %i.fas.fa-search.fa-lg
                %br/
                %br/
                %br/
                %br/

          %p{:align => "center", :style => "font-size: 20px"}
            %b Seleziona modalita:
          %br/
          #court
      .col-3
        %br/

app/views/matches/rate.js.haml
- if @m.tipo == 1
	$("##{@m.id}_1").html("#{j(render("showsolovssolo"))}")
- elsif @m.tipo == 2
	$("##{@m.id}_1").html("#{j(render("showsquadravssolo"))}")
- elsif @m.tipo == 3
	$("##{@m.id}_1").html("#{j(render("showsquadravssquadra"))}")
	

app/views/matches/show.js.haml
$("##{@m.id}_1").html("#{j(render("eventishow"))}")